### ISSUE TITLE
validateAccessTransformers just seems to fail?

### ISSUE THREAD

**Issue by Tslat** [neoforged/ModDevGradle#162]
Setting `validateAccessTransformers` to `true` in my build.gradle causes the refresh to fail for some reason I can't identify

On 2.0.30-beta, neoforge 21.1.57

```
*** Started working on transformSources
 ↳ Running external tool net.neoforged.jst:jst-cli-bundle:1.0.66
Last lines of FILEPATH\build\tmp\neoformruntime\20240922-181838_transformSources\console_output.txt:
------------------------------------------------------------
t.neoforged.neoforge.common.world.chunk.ForcedChunkManager.TicketTracker<net.minecraft.core.BlockPos>
Failed to create binary representation for type net.neoforged.neoforge.common.world.chunk.ForcedChunkManager.TicketTracker<java.util.UUID>
Failed to create binary representation for type net.neoforged.fml.common.asm.enumextension.ExtensionInfo
Failed to create binary representation for type net.neoforged.neoforge.common.world.ModifiableBiomeInfo
Failed to create binary representation for type net.neoforged.neoforge.common.world.ModifiableBiomeInfo
Failed to create binary representation for type net.neoforged.neoforge.attachment.AttachmentType<T>
Failed to create binary representation for type net.neoforged.neoforge.attachment.AttachmentType<T>
Failed to create binary representation for type net.neoforged.neoforge.attachment.AttachmentHolder.AsField
Failed to create binary representation for type net.neoforged.neoforge.attachment.AttachmentType<?>
Failed to create binary representation for type net.neoforged.neoforge.attachment.AttachmentType<T>
Failed to create binary representation for type net.neoforged.neoforge.attachment.AttachmentType<T>
Failed to create binary representation for type net.neoforged.neoforge.attachment.AttachmentType<T>
Failed to create binary representation for type net.neoforged.neoforge.attachment.AttachmentType<T>
Failed to create binary representation for type net.neoforged.neoforge.attachment.AttachmentHolder.AsField
Failed to create binary representation for type net.neoforged.neoforge.common.world.LevelChunkAuxiliaryLightManager
Failed to create binary representation for type net.neoforged.neoforge.event.level.AlterGroundEvent.StateProvider
Failed to create binary representation for type net.neoforged.neoforge.event.level.AlterGroundEvent.StateProvider
Failed to create binary representation for type net.neoforged.neoforge.fluids.FluidType
Failed to create binary representation for type net.neoforged.neoforge.common.world.ModifiableStructureInfo
Transformation failed

------------------------------------------------------------
Total runtime: 5.94s

net.neoforged.neoform.runtime.graph.NodeExecutionException: Node action for transformSources failed
	at net.neoforged.neoform.runtime.engine.NeoFormEngine.runNode(NeoFormEngine.java:458)
	at net.neoforged.neoform.runtime.engine.NeoFormEngine.lambda$getWaitCondition$3(NeoFormEngine.java:404)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
Caused by: java.lang.RuntimeException: Failed to execute tool
	at net.neoforged.neoform.runtime.actions.ExternalJavaToolAction.run(ExternalJavaToolAction.java:118)
	at net.neoforged.neoform.runtime.actions.ApplySourceTransformAction.run(ApplySourceTransformAction.java:127)
	at net.neoforged.neoform.runtime.engine.NeoFormEngine.runNode(NeoFormEngine.java:447)
	... 4 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createMinecraftArtifacts'.
```

**Comment by Matyrobbrt** [comment]
Are you sure all of your ats are valid and their target exists? It's a bit annoying that the information is buried by the failed to create representation messages (that should be fixed) but you can check the path of the log you're pointed to for the full log.

**Comment by Tslat** [comment]
Ah it's buried..

**Comment by Tslat** [comment]
Ok so _this_ is the error I'm getting in log

> targeting record class net.minecraft.world.level.levelgen.DensityFunctions$ShiftedNoise attempts to widen its access without widening the constructor's access. You must AT the constructor too: "public net.minecraft.world.level.levelgen.DensityFunctions$ShiftedNoise <init>(Lnet/minecraft/world/level/levelgen/DensityFunction;Lnet/minecraft/world/level/levelgen/DensityFunction;Lnet/minecraft/world/level/levelgen/DensityFunction;DDLnet/minecraft/world/level/levelgen/DensityFunction$NoiseHolder;)V"

The problem is - this is not true. This AT works perfectly fine, and is perfectly useable in code.

**Comment by Matyrobbrt** [comment]
That's correct, yes. ATing either the constructor or the record separately is an error state because it invisibly affects the other *just in dev*. Record constructors will have the same access as the record, therefore when applying the AT in dev we cannot modify the access of only one.

**Comment by Tslat** [comment]
Interesting

That's concerning that only gets picked up with the validation thing and not in normal AT usage lol
But ok, that adds up
